@startuml

' https://plantuml.com/ie-diagram
' https://stackoverflow.com/questions/46658847/crypto-currency-mysql-datatypes
' https://laravel.com/docs/4.2/eloquent#timestamps
' https://dev.mysql.com/doc/refman/8.0/en/json.html
' https://help.afas.nl/help/NL/SE/Sub_Config_Cycli.htm

entity "wp_pronamic_pay_customers" as customer {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* email : VARCHAR( 100 )
	wp_user_id : BIGINT(20) UNSIGNED <<fk>>
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	UNIQUE( email )
	INDEX( wp_user_id )
}

entity "wp_pronamic_pay_orders" as order {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* currency_code : VARCHAR(3)
	* total_amount : DECIMAL(27,18)
	shipping_amount : DECIMAL(27,18)
	* post_id : BIGINT(20) UNSIGNED <<fk>>
	* origin : VARCHAR(32)
	* origin_id : BIGINT(20)
	* status : VARCHAR(20)
	* test_mode : BOOL FALSE
	customer_id : BIGINT(20) UNSIGNED <<fk>>
	billing_address_id : BIGINT(20) UNSIGNED <<fk>>
	shipping_address_id : BIGINT(20) UNSIGNED <<fk>>
	subscription_id : BIGINT(20) UNSIGNED <<fk>>
	payment_method : VARCHAR(32)
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	INDEX( currency_code )
	INDEX( status )
	INDEX( billing_address_id )
	INDEX( shipping_address_id )
	INDEX( subscription_id )
	INDEX( origin )
	INDEX( origin_id )
	UNIQUE( origin, origin_id )
	INDEX( test_mode )
	INDEX( payment_method )
}

note left of order::origin
  origin or source?
end note

note left of order::origin_id
  origin_id or source_id?
end note

entity "wp_pronamic_pay_order_lines" as order_line {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* order_id : BIGINT(20) UNSIGNED <<fk>>
	* line_number : SMALLINT(5) UNSIGNED
	type : VARCHAR(32)
	sku : VARCHAR(255)
	name : VARCHAR(255)
	description : VARCHAR(255)
	quantity : SMALLINT(5) UNSIGNED
	unit_price : DECIMAL(27,18)
	discount_amount : DECIMAL(27,18)
	total_amount : DECIMAL(27,18)
	product_url : VARCHAR(255)
	image_url : VARCHAR(255)
	product_category : VARCHAR(255)
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	INDEX( order_id )
	UNIQUE( order_id, line_number )
}

entity "wp_pronamic_pay_subscriptions" as subscription {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* post_id : BIGINT(20) UNSIGNED <<fk>>
	* order_id : BIGINT(20) UNSIGNED <<fk>>
	* status : VARCHAR(20)
	* start_date : DATE
	end_date : DATE
	* amount : DECIMAL(27,18)
	payment_method : VARCHAR(32)
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	INDEX( status )
	INDEX( payment_method )
}

entity "wp_pronamic_pay_subscription_phases" as subscription_phase {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* subscription_id : BIGINT(20) UNSIGNED
	* sequence_number : INT(3) UNSIGNED
	* type : VARCHAR(20)
	* name : VARCHAR(255)
	* interval_unit : VARCHAR(1)
	* interval_value : INT(3) UNSIGNED
	times : INT(3) UNSIGNED

	__ indexes __
	PRIMARY( id )
}

note left of subscription_phase::interval_unit
  Options 'interval unit' or 'period designator'?
end note


entity "wp_pronamic_pay_subscription_periods" as subscription_period {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* subscription_id : BIGINT(20) UNSIGNED <<fk>>
	* phase_id : BIGINT(20) UNSIGNED <<fk>>
	* start_date : DATE
	* end_date : DATE
	* amount : DECIMAL(27,18)
	* type : VARCHAR(32)
	* status : VARCHAR(32)
	note : TEXT
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	INDEX( subscription_id )
	UNIQUE( subscription_id, start_date, end_date )
}

note right of subscription_period
  Or should we use 'billing cycle' instead of 'subscription period'?
end note

note left of subscription_period::type
  For example: 'regular', 'trial', 'sign-up'
end note

note left of subscription_period::status
  For example: 'open', 'pending', 'paid', 'refunded', 'failed', 'canceled'
end note

entity "wp_pronamic_pay_subscription_transactions" as subscription_transaction {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* subscription_id : BIGINT(20) UNSIGNED <<fk>>
	* subscription_period_id : BIGINT(20) UNSIGNED <<fk>>
	* transaction_id : BIGINT(20) UNSIGNED <<fk>>
}

entity "wp_pronamic_pay_transactions" as transaction {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* post_id : BIGINT(20) UNSIGNED <<fk>>
	* order_id : BIGINT(20) UNSIGNED <<fk>>
	* type: VARCHAR(32)
	* status : VARCHAR(20)
	* transaction_id : VARCHAR(255)
	* amount : DECIMAL(27,18)
	* test_mode : BOOL FALSE
	amount_refunded : DECIMAL(27,18)
	amount_remaining : DECIMAL(27,18)
	amount_captured : DECIMAL(27,18)
	authorized_at : DATETIME
	paid_at : DATETIME
	canceled_at : DATETIME
	expires_at : DATETIME
	expired_at : DATETIME
	failed_at : DATETIME
	payment_method : VARCHAR(32)
	invoice_number : VARCHAR(32)
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	INDEX( post_id )
	INDEX( type )
	INDEX( status )
	UNIQUE( transaction_id )
	INDEX( subscription_id )
	INDEX( subscription_period_id )
	INDEX( test_mode )
	INDEX( payment_method )
}

entity "wp_pronamic_pay_addresses" as address {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	name : VARCHAR(255)
	company_name : VARCHAR(255)
	line_1 : VARCHAR(255)
	line_2 : VARCHAR(255)
	street_name : VARCHAR(255)
	house_number : VARCHAR(255)
	postal_code : VARCHAR(255)
	company_name : VARCHAR(255)
	city : VARCHAR(255)
	country_code : VARCHAR(2)
	country_name : VARCHAR(255)
	latitude : DECIMAL(8,6)
	longitude DECIMAL(9,6)
	metadata : JSON
	__ indexes __
	PRIMARY( id )
	INDEX( country_code )
}

entity "wp_pronamic_pay_gateway_configurations" as gateway_configuration {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	metadata : JSON
	__ indexes __
	PRIMARY( id )
}

' https://github.com/woocommerce/woocommerce/blob/3.8.0/includes/log-handlers/class-wc-log-handler-db.php

entity "wp_pronamic_pay_log" as log {
	* <u>id</u> : BIGINT(20) UNSIGNED <<pk>>
	* created_at : DATETIME
	* updated_at : DATETIME
	* level : SMALLINT(4)
	* source : VARCHAR(200)
	* message : LONGTEXT
	context : LONGTEXT
	__ indexes __
	PRIMARY( id )
}

customer |o--o{ order
order --o| address : billing
order --o| address : shipping
order ||--o| subscription
order ||--o{ order_line
order ||--o{ transaction
subscription ||--o{ subscription_phase
subscription_phase ||--o{ subscription_period

subscription_transaction "0…*" |o--o{ "0…*" transaction

subscription_transaction "0…*" ||--o{ "0…*" subscription
note on link
A payment can be for multiple subscriptions.
end note

subscription_transaction "0…*" ||--o{ "0…*" subscription_period
note on link
A payment can be for multiple subscriptions and periods.
end note

@enduml
