@startuml

namespace Pronamic_Pay {
	class Gateway {
		start()
		payment()
	}
	
	class Config {
	
	}
	
	class GatewayFactory {
		register( $config_class, $gateway_class )
		create( Config $config )
	}
	
	Gateway <|-- Adyen
	Gateway <|-- IDealAdvanced
	Gateway <|-- IDealBasic
	Gateway <|-- Mollie
	Gateway <|-- MultiSafepay
	Gateway <|-- Ogone
	Gateway <|-- OmniKassa
	Gateway <|-- PayDutch
	Gateway <|-- Qantani
	Gateway <|-- Sisow
	Gateway <|-- TargetPay
}

namespace Pronamic_Pay_Gateways_Buckaroo {
	class Gateway {
	
	}
	
	class Config {
	
	}
	
	Pronamic_Pay.Gateway <|-- Gateway
	Pronamic_Pay.Config <|-- Config
}

namespace Pronamic_Pay_Gateways_Icepay {
	class Gateway {
	
	}
	
	class Config {
	
	}
	
	Pronamic_Pay.Gateway <|-- Gateway
	Pronamic_Pay.Config <|-- Config
}

@enduml
